version: "3.9"

services:
  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  grafana:
    image: grafana/grafana-enterprise
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./grafana-volume:/var/lib/grafana

  prometheus:
    image: ubuntu/prometheus
    ports:
      - 9090:9090
    environment:
      - TZ=UTC
    volumes:
      - ./prom/prometheus.yml:/etc/prometheus/prometheus.yml

  loki:
    image: grafana/loki:2.9.0
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-volume:/loki

  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo-data/tempo.yaml:/etc/tempo.yaml
      - ./tempo-data/tempo-volume:/tmp/tempo
    ports:
      - "3200:3200"   # tempo
      - "9095:9095" # tempo grpc
      - "4317:4317"  # otlp grpc
      - "4318:4318"  # otlp http
